### ISSUE TITLE
Implement $discord.disconnect

### ISSUE THREAD

**Issue by kawaii** [shuppet/raku-api-discord#56]
We should add a `disconnect` method which sends a `1000` close code to the websocket. This will allow for graceful shutdown of applications and prevent zombie connections while the heartbeats time out.

@gfldex asked about this in the Discord, just making a note of it here for later.

**Comment by Altreus** [comment]
Probably this https://github.com/shuppet/raku-api-discord/pull/58

Note optional `:script-mode` that handles SIGINT for you
